export enum Benefits {
    None = 0,
    MedicalInsurance = 1,
    DentalInsurance = 2,
    VisionInsurance = 3,
    JobTraining = 4,
    EducationAssistance = 5,
    PaidLeave = 6,
    EmployeeHousing = 7,
    EmployeeMeals = 8,
    EmployeeDiscounts = 9,
    DependentCareAssistance = 10,
    CommuterBenefits = 11,
    FlexibleSpendingAccount = 12,
    HealthSavingsAccount = 13,
    LifeInsurance = 14,
    PaidTimeOff = 15,
    FlexibleHours = 16,
    FourZeroOneK = 17,
    FringeBenefits = 18,
    Other = 19
}
